/**
 * The amino sign document this app builds must be byte-identical to what the
 * chain rebuilds, and its proto body identical to CosmJS.
 *
 * A one-byte disagreement produces a signature that verifies against nothing,
 * which the chain reports as an opaque "unauthorized" rather than as anything
 * the user or the developer can act on. zunia-core's Rust encoder is pinned to
 * the same vectors, so this file keeps the dashboard's TypeScript encoder from
 * drifting away from it.
 *
 * Vectors are generated by CosmJS; see zunia-core/tests/vectors/generate.
 * The file is vendored, byte for byte, from zunia-core
 * tests/vectors/cosmos-signing.json @ 0472167 (sha256 b0c65cf3…a1ed5de), so the
 * suite runs in CI without a zunia-core checkout. When zunia-core regenerates
 * its vectors, copy the file over again and update this line.
 *
 * CosmJS produced the documents and the proto bytes; the per-message amino
 * JSON is hand-written in the generator, and two of those values disagree with
 * what cosmoshub-4 verifies — proven against real on-chain signatures in
 * `chain-verified.test.ts`:
 * - `msg_vote`: the chain encodes `option` as the enum number (4), not
 *   "VOTE_OPTION_NO_WITH_VETO";
 * - `msg_transfer_no_timeout`: the chain always writes `timeout_height`, as
 *   `{}` when there is no height timeout.
 * For those two the vector's document is corrected the same way before the
 * comparison (`CHAIN_CORRECTIONS`), so every other byte stays pinned to the
 * vector, and the uncorrected vector is asserted not to match. Proto bytes are
 * compared as they are.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";

import {
  makeStdSignDoc,
  msgBeginRedelegate,
  msgDelegate,
  msgExecuteContract,
  msgIbcTransfer,
  msgProtoBytes,
  msgSend,
  msgUndelegate,
  msgVote,
  msgWithdrawReward,
  signDocBytes,
  type AminoMsg,
  type VoteOption,
} from "../amino-tx";
import { serializeAminoSignDoc } from "../bytes";

const VECTORS = join(import.meta.dirname, "vectors/cosmos-signing.json");

type Case = {
  name: string;
  amino: { sign_doc: string; sign_bytes_hex: string };
  direct: { msg_proto_hex: string };
};

const VOTE_OPTIONS: Record<string, VoteOption> = {
  VOTE_OPTION_YES: "yes",
  VOTE_OPTION_NO: "no",
  VOTE_OPTION_NO_WITH_VETO: "veto",
  VOTE_OPTION_ABSTAIN: "abstain",
};

const VOTE_NUMBERS: Record<string, number> = {
  VOTE_OPTION_YES: 1,
  VOTE_OPTION_ABSTAIN: 2,
  VOTE_OPTION_NO: 3,
  VOTE_OPTION_NO_WITH_VETO: 4,
};

type Doc = { msgs: { value: Record<string, unknown> }[] } & Record<string, unknown>;

/** The chain-verified corrections to two hand-written vector documents (see header). */
const CHAIN_CORRECTIONS: Partial<Record<string, (doc: Doc) => void>> = {
  msg_vote: (doc) => {
    const value = doc.msgs[0]!.value;
    value.option = VOTE_NUMBERS[String(value.option)];
  },
  msg_transfer_no_timeout: (doc) => {
    doc.msgs[0]!.value.timeout_height = {};
  },
};

/** Builders this app has. The Osmosis cases are pinned in direct-golden (their proto comes from osmojs). */
function builderFor(name: string, value: Record<string, never>): AminoMsg | null {
  const v = value as Record<string, never> & Record<string, string & never[]>;
  switch (name) {
    case "msg_send":
    case "msg_send_with_memo":
      return msgSend({ fromAddress: v.from_address, toAddress: v.to_address, amount: v.amount });
    case "msg_delegate":
      return msgDelegate({ delegatorAddress: v.delegator_address, validatorAddress: v.validator_address, amount: v.amount });
    case "msg_undelegate":
      return msgUndelegate({ delegatorAddress: v.delegator_address, validatorAddress: v.validator_address, amount: v.amount });
    case "msg_begin_redelegate":
      return msgBeginRedelegate({
        delegatorAddress: v.delegator_address,
        validatorSrcAddress: v.validator_src_address,
        validatorDstAddress: v.validator_dst_address,
        amount: v.amount,
      });
    case "msg_withdraw_delegator_reward":
      return msgWithdrawReward({ delegatorAddress: v.delegator_address, validatorAddress: v.validator_address });
    case "msg_vote":
      return msgVote({ proposalId: v.proposal_id, voter: v.voter, option: VOTE_OPTIONS[v.option]! });
    // The two the cross-chain swap path signs. MsgTransfer carries the memo
    // that makes every hop after the first happen, and MsgExecuteContract is
    // the `{"recover":{}}` call that pulls stranded swap output back out.
    case "msg_transfer_no_timeout":
    case "msg_transfer_with_timeout":
      return msgIbcTransfer({
        sourcePort: v.source_port,
        sourceChannel: v.source_channel,
        token: v.token,
        sender: v.sender,
        receiver: v.receiver,
        ...(v.timeout_timestamp ? { timeoutTimestamp: v.timeout_timestamp } : {}),
        ...(v.timeout_height ? { timeoutHeight: v.timeout_height } : {}),
        ...(v.memo ? { memo: v.memo } : {}),
      });
    case "msg_execute_contract":
      return msgExecuteContract({ sender: v.sender, contract: v.contract, msg: v.msg, funds: v.funds });
    default:
      return null;
  }
}

const vectors = JSON.parse(readFileSync(VECTORS, "utf8")) as { cases: Case[] };
let covered = 0;

for (const testCase of vectors.cases) {
  const reference = JSON.parse(testCase.amino.sign_doc) as Doc & {
    chain_id: string;
    account_number: string;
    sequence: string;
    fee: { amount: { denom: string; amount: string }[]; gas: string };
    memo: string;
  };
  const msg = builderFor(testCase.name, reference.msgs[0]!.value as Record<string, never>);
  if (!msg) continue;
  covered += 1;
  const correct = CHAIN_CORRECTIONS[testCase.name];

  test(`${testCase.name} amino sign bytes match ${correct ? "the chain-corrected vector" : "CosmJS"}`, () => {
    // Every input is taken from the vector's own sign document, so the encoder
    // is the only thing under test.
    const doc = makeStdSignDoc({
      chainId: reference.chain_id,
      accountNumber: reference.account_number,
      sequence: reference.sequence,
      fee: reference.fee,
      msgs: [msg],
      memo: reference.memo,
    });
    const actual = Buffer.from(signDocBytes(doc)).toString("hex");
    if (!correct) {
      assert.equal(actual, testCase.amino.sign_bytes_hex);
      return;
    }
    const corrected = JSON.parse(testCase.amino.sign_doc) as Doc;
    correct(corrected);
    assert.equal(actual, Buffer.from(serializeAminoSignDoc(corrected)).toString("hex"));
    assert.notEqual(actual, testCase.amino.sign_bytes_hex);
  });

  // The signed document and the broadcast body have to describe the same
  // message. A proto body that disagrees with it is rejected by the chain as
  // an opaque "unauthorized".
  test(`${testCase.name} proto body matches CosmJS`, () => {
    assert.equal(Buffer.from(msgProtoBytes(msg).value).toString("hex"), testCase.direct.msg_proto_hex);
  });
}

test("the vector file was found and actually exercised the builders", () => {
  // Ten: send ×2, delegate, undelegate, redelegate, withdraw, vote, transfer ×2, execute.
  assert.ok(covered >= 10, `expected at least 10 covered vectors, got ${covered}`);
});
