/**
 * The amino sign document this app builds must be byte-identical to CosmJS.
 *
 * A one-byte disagreement produces a signature that verifies against nothing,
 * which the chain reports as an opaque "unauthorized" rather than as anything
 * the user or the developer can act on. zunia-core's Rust encoder is pinned to
 * the same vectors, so this file keeps the dashboard's TypeScript encoder from
 * drifting away from it.
 *
 * Vectors are generated by CosmJS; see zunia-core/tests/vectors/generate.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";

import {
  makeStdSignDoc,
  msgDelegate,
  msgExecuteContract,
  msgIbcTransfer,
  msgProtoBytes,
  msgSend,
  msgVote,
  msgWithdrawReward,
  signDocBytes,
  type AminoMsg,
  type VoteOption,
} from "../amino-tx";

const VECTORS = join(
  import.meta.dirname,
  "../../../../../zunia-core/tests/vectors/cosmos-signing.json",
);

type Case = {
  name: string;
  amino: { sign_doc: string; sign_bytes_hex: string };
  direct: { msg_proto_hex: string };
};

const VOTE_OPTIONS: Record<string, VoteOption> = {
  VOTE_OPTION_YES: "yes",
  VOTE_OPTION_NO: "no",
  VOTE_OPTION_NO_WITH_VETO: "veto",
  VOTE_OPTION_ABSTAIN: "abstain",
};

/** Builders this app has. The rest of the vector set is covered in zunia-core. */
function builderFor(name: string, value: Record<string, never>): AminoMsg | null {
  const v = value as Record<string, never> & Record<string, string & never[]>;
  switch (name) {
    case "msg_send":
    case "msg_send_with_memo":
      return msgSend({
        fromAddress: v.from_address,
        toAddress: v.to_address,
        amount: v.amount,
      });
    case "msg_delegate":
      return msgDelegate({
        delegatorAddress: v.delegator_address,
        validatorAddress: v.validator_address,
        amount: v.amount,
      });
    case "msg_withdraw_delegator_reward":
      return msgWithdrawReward({
        delegatorAddress: v.delegator_address,
        validatorAddress: v.validator_address,
      });
    case "msg_vote":
      return msgVote({
        proposalId: v.proposal_id,
        voter: v.voter,
        option: VOTE_OPTIONS[v.option]!,
      });
    // The two the cross-chain swap path signs. MsgTransfer carries the memo
    // that makes every hop after the first happen, and MsgExecuteContract is
    // the `{"recover":{}}` call that pulls stranded swap output back out.
    case "msg_transfer_no_timeout":
    case "msg_transfer_with_timeout":
      return msgIbcTransfer({
        sourcePort: v.source_port,
        sourceChannel: v.source_channel,
        token: v.token,
        sender: v.sender,
        receiver: v.receiver,
        ...(v.timeout_timestamp
          ? { timeoutTimestamp: v.timeout_timestamp }
          : {}),
        ...(v.timeout_height ? { timeoutHeight: v.timeout_height } : {}),
        ...(v.memo ? { memo: v.memo } : {}),
      });
    case "msg_execute_contract":
      return msgExecuteContract({
        sender: v.sender,
        contract: v.contract,
        msg: v.msg,
        funds: v.funds,
      });
    default:
      return null;
  }
}

const vectors = JSON.parse(readFileSync(VECTORS, "utf8")) as { cases: Case[] };
let covered = 0;

for (const testCase of vectors.cases) {
  const reference = JSON.parse(testCase.amino.sign_doc) as {
    chain_id: string;
    account_number: string;
    sequence: string;
    fee: { amount: { denom: string; amount: string }[]; gas: string };
    memo: string;
    msgs: { value: Record<string, never> }[];
  };
  const msg = builderFor(testCase.name, reference.msgs[0]!.value);
  if (!msg) continue;
  covered += 1;

  test(`${testCase.name} amino sign bytes match CosmJS`, () => {
    // Every input is taken from the vector's own sign document, so the encoder
    // is the only thing under test.
    const doc = makeStdSignDoc({
      chainId: reference.chain_id,
      accountNumber: reference.account_number,
      sequence: reference.sequence,
      fee: reference.fee,
      msgs: [msg],
      memo: reference.memo,
    });
    assert.equal(
      Buffer.from(signDocBytes(doc)).toString("hex"),
      testCase.amino.sign_bytes_hex,
    );
  });

  // The signed document and the broadcast body have to describe the same
  // message. Only the document was pinned before; a proto body that disagrees
  // with it is rejected by the chain as an opaque "unauthorized", which is the
  // one failure neither the user nor the developer can act on.
  test(`${testCase.name} proto body matches CosmJS`, () => {
    assert.equal(
      Buffer.from(msgProtoBytes(msg).value).toString("hex"),
      testCase.direct.msg_proto_hex,
    );
  });
}

test("the vector file was found and actually exercised the builders", () => {
  // Eight: the five that were covered before, plus both MsgTransfer shapes and
  // MsgExecuteContract, which the cross-chain swap and its recovery sign.
  assert.ok(covered >= 8, `expected at least 8 covered vectors, got ${covered}`);
});
