/**
 * The amino sign document this app builds must be byte-identical to what the
 * chain rebuilds, and its proto body identical to CosmJS.
 *
 * A one-byte disagreement produces a signature that verifies against nothing,
 * which the chain reports as an opaque "unauthorized" rather than as anything
 * the user or the developer can act on. zunia-core's Rust encoder is pinned to
 * the same vectors, so this file keeps the dashboard's TypeScript encoder from
 * drifting away from it.
 *
 * Vectors are generated by CosmJS; see zunia-core/tests/vectors/generate.
 * The file is vendored, byte for byte, from zunia-core
 * tests/vectors/cosmos-signing.json @ 22ae866 (sha256 bd942ba5…cd563d4ff), so the
 * suite runs in CI without a zunia-core checkout. When zunia-core regenerates
 * its vectors, copy the file over again and update this line.
 *
 * No amino value in the file is written by hand any more: the generator
 * rebuilds each one from the case's proto bytes with the converter a CosmJS
 * client registers (@cosmjs/stargate, and osmojs for contract calls and
 * swaps). So the documents spell what cosmoshub-4 verifies, as the real
 * signatures in `chain-verified.test.ts` prove: a vote's `option` is the enum
 * number, and a transfer writes `timeout_height` as `{}` when it has no height
 * timeout. Every document and every proto body is compared as it is.
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";

import {
  makeStdSignDoc,
  msgBeginRedelegate,
  msgDelegate,
  msgExecuteContract,
  msgIbcTransfer,
  msgProtoBytes,
  msgSend,
  msgUndelegate,
  msgVote,
  msgWithdrawReward,
  signDocBytes,
  type AminoMsg,
  type VoteOption,
} from "../amino-tx";

const VECTORS = join(import.meta.dirname, "vectors/cosmos-signing.json");

type Case = {
  name: string;
  amino: { sign_doc: string; sign_bytes_hex: string };
  direct: { msg_proto_hex: string };
};

/** `cosmos.gov.v1beta1.VoteOption`, by the number the vectors (and the chain) write. */
const VOTE_OPTIONS: Record<number, VoteOption> = {
  1: "yes",
  2: "abstain",
  3: "no",
  4: "veto",
};

const OSMOSIS_SWAP =
  "an Osmosis poolmanager swap: osmosis.ts builds it, and src/lib/swap/__tests__/osmosis-proto.test.ts pins both its encodings to this same vector";

/**
 * The vector cases this file has no builder for, each with the reason. A case
 * that is in neither `builderFor` nor this list fails the suite, so a
 * regenerated vector file cannot bring in a message nobody decided about.
 */
const NOT_BUILT_HERE: Partial<Record<string, string>> = {
  msg_swap_exact_amount_in: OSMOSIS_SWAP,
  msg_swap_exact_amount_in_multi_hop: OSMOSIS_SWAP,
  msg_split_route_swap_exact_amount_in: OSMOSIS_SWAP,
};

/** Builders this app has, fed only what the vector's own document says. */
function builderFor(name: string, value: Record<string, never>): AminoMsg | null {
  const v = value as Record<string, never> & Record<string, string & never[]>;
  switch (name) {
    case "msg_send":
    case "msg_send_with_memo":
    // `&`, `<` and `>` in the memo: the document escapes them as Go does.
    case "msg_send_memo_html":
    // A 32-byte recipient (a contract, an interchain account): bech32 like any other.
    case "msg_send_to_32_byte":
      return msgSend({ fromAddress: v.from_address, toAddress: v.to_address, amount: v.amount });
    case "msg_delegate":
      return msgDelegate({ delegatorAddress: v.delegator_address, validatorAddress: v.validator_address, amount: v.amount });
    case "msg_undelegate":
      return msgUndelegate({ delegatorAddress: v.delegator_address, validatorAddress: v.validator_address, amount: v.amount });
    case "msg_begin_redelegate":
      return msgBeginRedelegate({
        delegatorAddress: v.delegator_address,
        validatorSrcAddress: v.validator_src_address,
        validatorDstAddress: v.validator_dst_address,
        amount: v.amount,
      });
    case "msg_withdraw_delegator_reward":
      return msgWithdrawReward({ delegatorAddress: v.delegator_address, validatorAddress: v.validator_address });
    case "msg_vote":
      return msgVote({ proposalId: v.proposal_id, voter: v.voter, option: VOTE_OPTIONS[Number(v.option)]! });
    // The two the cross-chain swap path signs. MsgTransfer carries the memo
    // that makes every hop after the first happen, and MsgExecuteContract is
    // the `{"recover":{}}` call that pulls stranded swap output back out.
    case "msg_transfer_no_timeout":
    case "msg_transfer_with_timeout":
    case "msg_transfer_timestamp_only":
      return msgIbcTransfer({
        sourcePort: v.source_port,
        sourceChannel: v.source_channel,
        token: v.token,
        sender: v.sender,
        receiver: v.receiver,
        ...(v.timeout_timestamp ? { timeoutTimestamp: v.timeout_timestamp } : {}),
        // The vector writes `timeout_height: {}` when there is no height
        // timeout; the builder has to write it without being handed one.
        ...(Object.keys(v.timeout_height ?? {}).length > 0 ? { timeoutHeight: v.timeout_height } : {}),
        ...(v.memo ? { memo: v.memo } : {}),
      });
    case "msg_execute_contract":
    // `{"recover":{}}` on a 32-byte contract, with no funds: the builder
    // writes `funds: []` without being handed it.
    case "msg_execute_contract_32_no_funds":
    // A CW721 transfer whose token id holds `&`: escaped in the sign
    // document, written as it is in the proto `msg` bytes.
    case "msg_execute_contract_nft_html": {
      const funds: readonly unknown[] = v.funds;
      return msgExecuteContract({
        sender: v.sender,
        contract: v.contract,
        msg: v.msg,
        ...(funds.length > 0 ? { funds: v.funds } : {}),
      });
    }
    default:
      return null;
  }
}

const vectors = JSON.parse(readFileSync(VECTORS, "utf8")) as { cases: Case[] };
let covered = 0;

for (const testCase of vectors.cases) {
  const reference = JSON.parse(testCase.amino.sign_doc) as {
    chain_id: string;
    account_number: string;
    sequence: string;
    fee: { amount: { denom: string; amount: string }[]; gas: string };
    memo: string;
    msgs: { value: Record<string, unknown> }[];
  };
  const msg = builderFor(testCase.name, reference.msgs[0]!.value as Record<string, never>);
  if (!msg) {
    test(`${testCase.name} amino sign bytes match CosmJS`, { skip: NOT_BUILT_HERE[testCase.name] ?? false }, () => {
      assert.fail(`${testCase.name} has no builder here and no reason in NOT_BUILT_HERE`);
    });
    continue;
  }
  covered += 1;

  test(`${testCase.name} amino sign bytes match CosmJS`, () => {
    // Every input is taken from the vector's own sign document, so the encoder
    // is the only thing under test.
    const doc = makeStdSignDoc({
      chainId: reference.chain_id,
      accountNumber: reference.account_number,
      sequence: reference.sequence,
      fee: reference.fee,
      msgs: [msg],
      memo: reference.memo,
    });
    assert.equal(Buffer.from(signDocBytes(doc)).toString("hex"), testCase.amino.sign_bytes_hex);
  });

  // The signed document and the broadcast body have to describe the same
  // message. A proto body that disagrees with it is rejected by the chain as
  // an opaque "unauthorized".
  test(`${testCase.name} proto body matches CosmJS`, () => {
    assert.equal(Buffer.from(msgProtoBytes(msg).value).toString("hex"), testCase.direct.msg_proto_hex);
  });
}

test("the vector file was found and actually exercised the builders", () => {
  // Fifteen: send ×4, delegate, undelegate, redelegate, withdraw, vote,
  // transfer ×3, execute ×3. The other three are the Osmosis swaps.
  assert.equal(covered, 15);
  assert.equal(vectors.cases.length, covered + Object.keys(NOT_BUILT_HERE).length);
});
